// GENERATED by scripts/gen_level_model.py from artifacts/env/ls20/level2.json; do not edit.
// Rule-level model of ARC-AGI-3 public environment ls20-9607627b, level 2.
// Constants from the shipped level data; rules from reading the shipped source
// (see the generator's docstring). No escape constructs; see scripts/check_model.sh.
module Ls20Level2 {
  const W: int := 12
  const H: int := 12
  const START_X: int := 5
  const START_Y: int := 8
  const START_ROT: int := 0
  const GOAL_X: int := 2
  const GOAL_Y: int := 8
  const GOAL_ROT: int := 3
  const ROT_TILE_X: int := 9
  const ROT_TILE_Y: int := 9
  const STEPS: int := 42
  const DEC: int := 2
  const LIVES: int := 3
  const NE: int := 2          // energy pickups on this level
  const TILE_FLASH: bool := false  // cycling a tile into a match is free (level 1 only)

  // Wall cells, from the shipped level data (one disjunct per cell).
  predicate IsWall(x: int, y: int) {
    (x == 0 && y == 0)
    || (x == 0 && y == 1)
    || (x == 0 && y == 2)
    || (x == 0 && y == 3)
    || (x == 0 && y == 4)
    || (x == 0 && y == 5)
    || (x == 0 && y == 6)
    || (x == 0 && y == 7)
    || (x == 0 && y == 8)
    || (x == 0 && y == 9)
    || (x == 0 && y == 10)
    || (x == 0 && y == 11)
    || (x == 1 && y == 0)
    || (x == 1 && y == 1)
    || (x == 1 && y == 5)
    || (x == 1 && y == 6)
    || (x == 1 && y == 7)
    || (x == 1 && y == 8)
    || (x == 1 && y == 9)
    || (x == 1 && y == 10)
    || (x == 1 && y == 11)
    || (x == 2 && y == 0)
    || (x == 2 && y == 1)
    || (x == 2 && y == 9)
    || (x == 2 && y == 10)
    || (x == 2 && y == 11)
    || (x == 3 && y == 0)
    || (x == 3 && y == 5)
    || (x == 3 && y == 6)
    || (x == 3 && y == 7)
    || (x == 3 && y == 8)
    || (x == 3 && y == 9)
    || (x == 3 && y == 10)
    || (x == 3 && y == 11)
    || (x == 4 && y == 0)
    || (x == 4 && y == 3)
    || (x == 4 && y == 4)
    || (x == 4 && y == 5)
    || (x == 4 && y == 6)
    || (x == 4 && y == 7)
    || (x == 4 && y == 8)
    || (x == 4 && y == 9)
    || (x == 4 && y == 10)
    || (x == 4 && y == 11)
    || (x == 5 && y == 0)
    || (x == 5 && y == 5)
    || (x == 5 && y == 6)
    || (x == 5 && y == 9)
    || (x == 5 && y == 10)
    || (x == 5 && y == 11)
    || (x == 6 && y == 0)
    || (x == 6 && y == 9)
    || (x == 6 && y == 10)
    || (x == 6 && y == 11)
    || (x == 7 && y == 0)
    || (x == 7 && y == 3)
    || (x == 7 && y == 4)
    || (x == 7 && y == 7)
    || (x == 7 && y == 8)
    || (x == 7 && y == 9)
    || (x == 7 && y == 11)
    || (x == 8 && y == 0)
    || (x == 8 && y == 4)
    || (x == 8 && y == 5)
    || (x == 8 && y == 6)
    || (x == 8 && y == 7)
    || (x == 8 && y == 11)
    || (x == 9 && y == 0)
    || (x == 9 && y == 11)
    || (x == 10 && y == 0)
    || (x == 10 && y == 1)
    || (x == 10 && y == 2)
    || (x == 10 && y == 3)
    || (x == 10 && y == 6)
    || (x == 10 && y == 11)
    || (x == 11 && y == 0)
    || (x == 11 && y == 1)
    || (x == 11 && y == 2)
    || (x == 11 && y == 3)
    || (x == 11 && y == 4)
    || (x == 11 && y == 5)
    || (x == 11 && y == 6)
    || (x == 11 && y == 7)
    || (x == 11 && y == 8)
    || (x == 11 && y == 9)
    || (x == 11 && y == 10)
    || (x == 11 && y == 11)
  }

  // Index of the energy pickup on this cell, or -1.
  function EnergyIndex(x: int, y: int): int
    ensures -1 <= EnergyIndex(x, y) < 2
  {
    if x == 2 && y == 3 then 0 else if x == 7 && y == 10 then 1 else -1
  }

  // The 4 legal value(s) of the energy bitmask for NE = 2.
  predicate EatenLegal(m: nat) { m == 0 || m == 1 || m == 2 || m == 3 }

  function AddBit(m: nat, i: int): nat
    requires 0 <= i < NE
  {
    if i == 0 then m + 1 else if i == 1 then m + 2 else m
  }

  predicate HasBit(m: nat, i: int)
    requires 0 <= i < NE
  {
    if i == 0 then (m / 1) % 2 == 1 else if i == 1 then (m / 2) % 2 == 1 else false
  }

  datatype Status = Play | Win | Over
  datatype S = S(x: int, y: int, rot: int, lives: int, steps: int, eaten: nat, status: Status)

  predicate Legal(s: S) {
    0 <= s.x < W && 0 <= s.y < H && !IsWall(s.x, s.y) && 0 <= s.rot < 4
    && 1 <= s.lives <= LIVES && -DEC <= s.steps <= STEPS && EatenLegal(s.eaten)
  }

  function Start(): S { S(START_X, START_Y, START_ROT, LIVES, STEPS, 0, Play) }

  lemma StartLegal() ensures Legal(Start()) {}

  function Delta(a: int): (int, int)
  { if a == 1 then (0, -1) else if a == 2 then (0, 1) else if a == 3 then (-1, 0)
     else if a == 4 then (1, 0) else (0, 0) }

  predicate Matches(rot: int) { rot == GOAL_ROT }

  // One action on a Play state. Mirrors Ls20.step() at the rule level.
  // TOTAL in the action: an action outside the movement set leaves the state
  // untouched, which is what the shipped game does -- it completes the action
  // and returns before the step counter is touched.
  function Step(s: S, a: int): S
  {
    if s.status != Play || a < 1 || a > 4 then s else
    var d := Delta(a);
    var tx := s.x + d.0;
    var ty := s.y + d.1;
    var isWall := IsWall(tx, ty);
    var isGoal := tx == GOAL_X && ty == GOAL_Y;
    var isRot := tx == ROT_TILE_X && ty == ROT_TILE_Y;
    var ei := EnergyIndex(tx, ty);
    var gotEnergy := !isWall && ei >= 0 && ei < NE && !HasBit(s.eaten, ei);
    var rot' := if !isWall && isRot then (s.rot + 1) % 4 else s.rot;
    // A flash consumes the action at no step cost: a goal reached with the wrong
    // rotation always flashes; a tile cycled into a match flashes on level 1 only.
    var flash := (!isWall && isGoal && !Matches(s.rot))
              || (TILE_FLASH && !isWall && isRot && Matches(rot'));
    var blocked := isWall || (isGoal && !Matches(s.rot));
    var x' := if blocked then s.x else tx;
    var y' := if blocked then s.y else ty;
    var eaten' := if gotEnergy then AddBit(s.eaten, ei) else s.eaten;
    if flash then S(x', y', rot', s.lives, s.steps, eaten', Play) else
    // An energy pickup refills the counter and skips this move's decrement.
    if gotEnergy then S(x', y', rot', s.lives, STEPS, eaten', Play) else
    var steps' := if s.steps >= 0 then s.steps - DEC else s.steps;
    var ranOut := steps' < 0;
    var won := x' == GOAL_X && y' == GOAL_Y && Matches(rot');
    if won then S(x', y', rot', s.lives, steps', eaten', Win) else
    if ranOut then (
      if s.lives - 1 == 0 then S(x', y', rot', 0, steps', eaten', Over)
      else S(START_X, START_Y, START_ROT, s.lives - 1, STEPS, 0, Play))
    else S(x', y', rot', s.lives, steps', eaten', Play)
  }

  function Reset(s: S): S { Start() }

  // Indexed rather than sliced: slicing a 45-element literal sequence put the
  // prover into work it could not finish, and an unfinished obligation is
  // unknown, not discharged.
  function RunFrom(s: S, path: seq<int>, i: nat): S
    requires i <= |path|
    decreases |path| - i
  { if i == |path| then s else RunFrom(Step(s, path[i]), path, i + 1) }

  function Run(s: S, path: seq<int>): S { RunFrom(s, path, 0) }

  // A non-movement action changes nothing (the shipped game returns before the
  // step counter is touched); this is what makes Step total.
  lemma NoOpAction(s: S, a: int)
    requires a < 1 || a > 4
    ensures Step(s, a) == s
  {}

  // E2: no action leaves the legal state space (an Over state is terminal and
  // carries lives = 0). The player is never on a wall cell and the border is
  // walled, so a legal position is interior and every neighbour is in range.
  predicate LegalOrOver(s: S) { Legal(s) || (s.status == Over && s.lives == 0) }

  lemma E2_Closure(s: S, a: int)
    requires Legal(s)
    ensures LegalOrOver(Step(s, a))
  {
    if 1 <= a <= 4 {
      BorderFacts();
      assert 1 <= s.x <= W - 2 && 1 <= s.y <= H - 2;
    }
    EatenBound(s, a);
  }

  // The eaten bitmask stays legal: a pickup is consumed at most once, and the
  // mask space is enumerated explicitly (it has at most 2^NE elements, NE small),
  // so this is decided by case analysis rather than nonlinear arithmetic.
  lemma EatenBound(s: S, a: int)
    requires Legal(s)
    ensures EatenLegal(Step(s, a).eaten)
  {
    if 1 <= a <= 4 {
      var d := Delta(a);
      var ei := EnergyIndex(s.x + d.0, s.y + d.1);
      if 0 <= ei < NE && !HasBit(s.eaten, ei) {
        EatenClosure(s.eaten, ei);
      }
    }
  }

  lemma EatenClosure(m: nat, i: int)
    requires EatenLegal(m) && 0 <= i < NE && !HasBit(m, i)
    ensures EatenLegal(AddBit(m, i))
  {}

  // The extracted wall set contains the whole border of the W x H lattice.
  lemma BorderFacts()
    ensures forall x :: 0 <= x < W ==> IsWall(x, 0) && IsWall(x, H - 1)
    ensures forall y :: 0 <= y < H ==> IsWall(0, y) && IsWall(W - 1, y)
  {
    forall x | 0 <= x < W ensures IsWall(x, 0) && IsWall(x, H - 1) {
      if x == 0 { } else if x == 1 { } else if x == 2 { } else if x == 3 { } else if x == 4 { } else if x == 5 { } else if x == 6 { } else if x == 7 { } else if x == 8 { } else if x == 9 { } else if x == 10 { } else if x == 11 { }
    }
    forall y | 0 <= y < H ensures IsWall(0, y) && IsWall(W - 1, y) {
      if y == 0 { } else if y == 1 { } else if y == 2 { } else if y == 3 { } else if y == 4 { } else if y == 5 { } else if y == 6 { } else if y == 7 { } else if y == 8 { } else if y == 9 { } else if y == 10 { } else if y == 11 { }
    }
  }

  // E3: reset restores the start state (by definition in the model; the shipped
  // implementation is probed directly by scripts/state_graph.py).
  lemma E3_Reset(s: S) ensures Reset(s) == Start() {}

  // E1: winnable. WITNESS is the shortest winning action sequence found by
  // enumerating the SHIPPED game; each intermediate state asserted below is
  // that game's actual state after those actions, so the proof checks the
  // model against the implementation at every step of the winning path.
  // The last state is checked on status alone: the shipped game has loaded
  // the next level by then, which this model does not cover.
  const WITNESS: seq<int> := [1, 4, 1, 1, 1, 1, 1, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2, 1, 2, 2, 3, 3, 4, 1, 4, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 2, 2, 2]  // 45 actions

  function Chunk0(s: S): S { Step(Step(Step(Step(Step(Step(Step(Step(Step(Step(s, 1), 4), 1), 1), 1), 1), 1), 4), 4), 2) }
  function Chunk1(s: S): S { Step(Step(Step(Step(Step(Step(Step(Step(Step(Step(s, 4), 2), 2), 2), 2), 2), 2), 1), 2), 2) }
  function Chunk2(s: S): S { Step(Step(Step(Step(Step(Step(Step(Step(Step(Step(s, 3), 3), 4), 1), 4), 1), 1), 1), 1), 1) }
  function Chunk3(s: S): S { Step(Step(Step(Step(Step(Step(Step(Step(Step(Step(s, 1), 1), 3), 3), 3), 3), 3), 3), 2), 3) }
  function Chunk4(s: S): S { Step(Step(Step(Step(Step(s, 2), 2), 2), 2), 2) }

  function PlayWitness(s: S): S { Chunk4(Chunk3(Chunk2(Chunk1(Chunk0(s))))) }

  lemma E1_Chunk0()
    ensures Chunk0(S(5, 8, 0, 3, 42, 0, Play)) == S(8, 3, 0, 3, 22, 0, Play)
  {
    var s0 := S(5, 8, 0, 3, 42, 0, Play);
    var s1 := Step(s0, 1);
    assert s1 == S(5, 7, 0, 3, 40, 0, Play);  // the shipped game after 1 action(s)
    var s2 := Step(s1, 4);
    assert s2 == S(6, 7, 0, 3, 38, 0, Play);  // the shipped game after 2 action(s)
    var s3 := Step(s2, 1);
    assert s3 == S(6, 6, 0, 3, 36, 0, Play);  // the shipped game after 3 action(s)
    var s4 := Step(s3, 1);
    assert s4 == S(6, 5, 0, 3, 34, 0, Play);  // the shipped game after 4 action(s)
    var s5 := Step(s4, 1);
    assert s5 == S(6, 4, 0, 3, 32, 0, Play);  // the shipped game after 5 action(s)
    var s6 := Step(s5, 1);
    assert s6 == S(6, 3, 0, 3, 30, 0, Play);  // the shipped game after 6 action(s)
    var s7 := Step(s6, 1);
    assert s7 == S(6, 2, 0, 3, 28, 0, Play);  // the shipped game after 7 action(s)
    var s8 := Step(s7, 4);
    assert s8 == S(7, 2, 0, 3, 26, 0, Play);  // the shipped game after 8 action(s)
    var s9 := Step(s8, 4);
    assert s9 == S(8, 2, 0, 3, 24, 0, Play);  // the shipped game after 9 action(s)
    var s10 := Step(s9, 2);
    assert s10 == S(8, 3, 0, 3, 22, 0, Play);  // the shipped game after 10 action(s)
  }

  lemma E1_Chunk1()
    ensures Chunk1(S(8, 3, 0, 3, 22, 0, Play)) == S(9, 10, 2, 3, 2, 0, Play)
  {
    var s10 := S(8, 3, 0, 3, 22, 0, Play);
    var s11 := Step(s10, 4);
    assert s11 == S(9, 3, 0, 3, 20, 0, Play);  // the shipped game after 11 action(s)
    var s12 := Step(s11, 2);
    assert s12 == S(9, 4, 0, 3, 18, 0, Play);  // the shipped game after 12 action(s)
    var s13 := Step(s12, 2);
    assert s13 == S(9, 5, 0, 3, 16, 0, Play);  // the shipped game after 13 action(s)
    var s14 := Step(s13, 2);
    assert s14 == S(9, 6, 0, 3, 14, 0, Play);  // the shipped game after 14 action(s)
    var s15 := Step(s14, 2);
    assert s15 == S(9, 7, 0, 3, 12, 0, Play);  // the shipped game after 15 action(s)
    var s16 := Step(s15, 2);
    assert s16 == S(9, 8, 0, 3, 10, 0, Play);  // the shipped game after 16 action(s)
    var s17 := Step(s16, 2);
    assert s17 == S(9, 9, 1, 3, 8, 0, Play);  // the shipped game after 17 action(s)
    var s18 := Step(s17, 1);
    assert s18 == S(9, 8, 1, 3, 6, 0, Play);  // the shipped game after 18 action(s)
    var s19 := Step(s18, 2);
    assert s19 == S(9, 9, 2, 3, 4, 0, Play);  // the shipped game after 19 action(s)
    var s20 := Step(s19, 2);
    assert s20 == S(9, 10, 2, 3, 2, 0, Play);  // the shipped game after 20 action(s)
  }

  lemma E1_Chunk2()
    ensures Chunk2(S(9, 10, 2, 3, 2, 0, Play)) == S(9, 4, 3, 3, 26, 2, Play)
  {
    var s20 := S(9, 10, 2, 3, 2, 0, Play);
    var s21 := Step(s20, 3);
    assert s21 == S(8, 10, 2, 3, 0, 0, Play);  // the shipped game after 21 action(s)
    var s22 := Step(s21, 3);
    assert s22 == S(7, 10, 2, 3, 42, 2, Play);  // the shipped game after 22 action(s)
    var s23 := Step(s22, 4);
    assert s23 == S(8, 10, 2, 3, 40, 2, Play);  // the shipped game after 23 action(s)
    var s24 := Step(s23, 1);
    assert s24 == S(8, 9, 2, 3, 38, 2, Play);  // the shipped game after 24 action(s)
    var s25 := Step(s24, 4);
    assert s25 == S(9, 9, 3, 3, 36, 2, Play);  // the shipped game after 25 action(s)
    var s26 := Step(s25, 1);
    assert s26 == S(9, 8, 3, 3, 34, 2, Play);  // the shipped game after 26 action(s)
    var s27 := Step(s26, 1);
    assert s27 == S(9, 7, 3, 3, 32, 2, Play);  // the shipped game after 27 action(s)
    var s28 := Step(s27, 1);
    assert s28 == S(9, 6, 3, 3, 30, 2, Play);  // the shipped game after 28 action(s)
    var s29 := Step(s28, 1);
    assert s29 == S(9, 5, 3, 3, 28, 2, Play);  // the shipped game after 29 action(s)
    var s30 := Step(s29, 1);
    assert s30 == S(9, 4, 3, 3, 26, 2, Play);  // the shipped game after 30 action(s)
  }

  lemma E1_Chunk3()
    ensures Chunk3(S(9, 4, 3, 3, 26, 2, Play)) == S(2, 3, 3, 3, 42, 3, Play)
  {
    var s30 := S(9, 4, 3, 3, 26, 2, Play);
    var s31 := Step(s30, 1);
    assert s31 == S(9, 3, 3, 3, 24, 2, Play);  // the shipped game after 31 action(s)
    var s32 := Step(s31, 1);
    assert s32 == S(9, 2, 3, 3, 22, 2, Play);  // the shipped game after 32 action(s)
    var s33 := Step(s32, 3);
    assert s33 == S(8, 2, 3, 3, 20, 2, Play);  // the shipped game after 33 action(s)
    var s34 := Step(s33, 3);
    assert s34 == S(7, 2, 3, 3, 18, 2, Play);  // the shipped game after 34 action(s)
    var s35 := Step(s34, 3);
    assert s35 == S(6, 2, 3, 3, 16, 2, Play);  // the shipped game after 35 action(s)
    var s36 := Step(s35, 3);
    assert s36 == S(5, 2, 3, 3, 14, 2, Play);  // the shipped game after 36 action(s)
    var s37 := Step(s36, 3);
    assert s37 == S(4, 2, 3, 3, 12, 2, Play);  // the shipped game after 37 action(s)
    var s38 := Step(s37, 3);
    assert s38 == S(3, 2, 3, 3, 10, 2, Play);  // the shipped game after 38 action(s)
    var s39 := Step(s38, 2);
    assert s39 == S(3, 3, 3, 3, 8, 2, Play);  // the shipped game after 39 action(s)
    var s40 := Step(s39, 3);
    assert s40 == S(2, 3, 3, 3, 42, 3, Play);  // the shipped game after 40 action(s)
  }

  lemma E1_Chunk4()
    ensures Chunk4(S(2, 3, 3, 3, 42, 3, Play)).status == Win
  {
    var s40 := S(2, 3, 3, 3, 42, 3, Play);
    var s41 := Step(s40, 2);
    assert s41 == S(2, 4, 3, 3, 40, 3, Play);  // the shipped game after 41 action(s)
    var s42 := Step(s41, 2);
    assert s42 == S(2, 5, 3, 3, 38, 3, Play);  // the shipped game after 42 action(s)
    var s43 := Step(s42, 2);
    assert s43 == S(2, 6, 3, 3, 36, 3, Play);  // the shipped game after 43 action(s)
    var s44 := Step(s43, 2);
    assert s44 == S(2, 7, 3, 3, 34, 3, Play);  // the shipped game after 44 action(s)
    var s45 := Step(s44, 2);
    assert s45.status == Win;
  }

  lemma E1_Winnable()
    ensures |WITNESS| == 45
    ensures PlayWitness(Start()).status == Win
  {
    assert Start() == S(5, 8, 0, 3, 42, 0, Play);
    E1_Chunk0();
    E1_Chunk1();
    E1_Chunk2();
    E1_Chunk3();
    E1_Chunk4();
  }

  // Oracle entry points (compiled to JavaScript and called by the differential).
  function Apply(x: int, y: int, rot: int, lives: int, steps: int, eaten: nat, status: int, a: int): S
  { Step(S(x, y, rot, lives, steps, eaten, if status == 0 then Play else if status == 1 then Win else Over), a) }
  function StatusCode(s: S): int { match s.status case Play => 0 case Win => 1 case Over => 2 }
}
