"""Render docs/CLAIMS.md from docs/claims.json (never hand-edit CLAIMS.md)."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
claims = json.loads((ROOT / "docs" / "claims.json").read_text())
L = ["# Claims register (generated by scripts/claims_md.py from docs/claims.json)\n",
     "Every load-bearing number in FINDINGS.md, tied to the artefact line that produced it. Checked by `scripts/report_check.sh docs/claims.json`.\n",
     "| # | value | artefact | line pattern | produced by |", "|---|---|---|---|---|"]
for i, c in enumerate(claims):
    L.append(f"| {i} | `{c['value']}` | `{c['log']}` | `{c['pattern']}` | {c.get('by', '')} |")
(ROOT / "docs" / "CLAIMS.md").write_text("\n".join(L) + "\n")
print(f"wrote docs/CLAIMS.md ({len(claims)} claims)")
