"""Generate model/ls20_level<k>.dfy from artifacts/env/ls20/level<k>.json.

The RULES below are hand-written from reading the shipped ls20 source
(step / txnfzvzetn / on_set_level / the step-counter display class) at the
rule level: walls block; the goal blocks unless the piece matches and then
completes the level; a rotation tile cycles the rotation; a move that ends in
a "flash" (goal mismatch, or a modifier tile producing a match on level 1)
costs no step; every other move, blocked or not, costs one step; running out
of steps costs a life and restores the start layout; three lives.
The CONSTANTS come from the JSON (the shipped level data), never by hand.
Levels with energy, pushers or patrols are not covered by this generator.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TEMPLATE = r'''// GENERATED by scripts/gen_level_model.py from {json_rel}; do not edit.
// Rule-level model of ARC-AGI-3 public environment {game}, level {level}.
// No escape constructs (checked by scripts/check_model.sh).
module Ls20Level{level} {{
  const W: int := {cells_x}
  const H: int := {cells_y}
  const START_X: int := {sx}
  const START_Y: int := {sy}
  const START_ROT: int := {srot}
  const GOAL_X: int := {gx}
  const GOAL_Y: int := {gy}
  const GOAL_ROT: int := {grot}
  const ROT_TILE_X: int := {rx}
  const ROT_TILE_Y: int := {ry}
  const STEPS: int := {steps}
  const DEC: int := {dec}
  const LIVES: int := {lives}
  // Wall cells, from the shipped level data (one disjunct per cell).
  predicate IsWall(x: int, y: int) {{
    {walls}
  }}

  datatype Status = Play | Win | Over
  datatype S = S(x: int, y: int, rot: int, lives: int, steps: int, status: Status)

  predicate Legal(s: S) {{
    0 <= s.x < W && 0 <= s.y < H && !IsWall(s.x, s.y) && 0 <= s.rot < 4 && 1 <= s.lives <= LIVES && -DEC <= s.steps <= STEPS
  }}

  lemma StartLegal() ensures Legal(Start()) {{}}


  function Start(): S {{ S(START_X, START_Y, START_ROT, LIVES, STEPS, Play) }}

  function Delta(a: int): (int, int)
    requires 1 <= a <= 4
  {{ if a == 1 then (0, -1) else if a == 2 then (0, 1) else if a == 3 then (-1, 0) else (1, 0) }}

  predicate Matches(rot: int) {{ rot == GOAL_ROT }}

  // One action on a Play state. Mirrors Ls20.step() at the rule level.
  function Step(s: S, a: int): S
    requires 1 <= a <= 4
  {{
    if s.status != Play then s else
    var d := Delta(a);
    var tx := s.x + d.0;
    var ty := s.y + d.1;
    var isWall := IsWall(tx, ty);
    var isGoal := tx == GOAL_X && ty == GOAL_Y;
    var isRot := tx == ROT_TILE_X && ty == ROT_TILE_Y;
    // rotation tile: cycle; on level 1 a resulting match "flashes" (no step cost)
    var rot' := if !isWall && isRot then (s.rot + 1) % 4 else s.rot;
    var flash := (!isWall && isGoal && !Matches(s.rot)) || (!isWall && isRot && Matches(rot'));
    var blocked := isWall || (isGoal && !Matches(s.rot));
    var x' := if blocked then s.x else tx;
    var y' := if blocked then s.y else ty;
    if flash then S(x', y', rot', s.lives, s.steps, Play) else
    var steps' := if s.steps >= 0 then s.steps - DEC else s.steps;
    var ranOut := steps' < 0;
    var won := x' == GOAL_X && y' == GOAL_Y && Matches(rot');
    if won then S(x', y', rot', s.lives, steps', Win) else
    if ranOut then (
      if s.lives - 1 == 0 then S(x', y', rot', 0, steps', Over)
      else S(START_X, START_Y, START_ROT, s.lives - 1, STEPS, Play))
    else S(x', y', rot', s.lives, steps', Play)
  }}

  function Reset(s: S): S {{ Start() }}

  function Run(s: S, path: seq<int>): S
    requires forall i :: 0 <= i < |path| ==> 1 <= path[i] <= 4
    decreases |path|
  {{ if |path| == 0 then s else Run(Step(s, path[0]), path[1..]) }}

  // E2: no action leaves the legal state space (Over states carry lives = 0 and are terminal).
  predicate LegalOrOver(s: S) {{ Legal(s) || (s.status == Over && s.lives == 0) }}

  lemma E2_Closure(s: S, a: int)
    requires 1 <= a <= 4
    requires Legal(s)
    ensures LegalOrOver(Step(s, a))
  {{
    // The player never stands on a wall cell and the border is walled, so a
    // legal position is interior and every neighbour is in range; a blocked
    // move keeps the position, an unblocked one lands on a non-wall cell.
    BorderFacts();
    assert 1 <= s.x <= W - 2 && 1 <= s.y <= H - 2;
  }}

{border_facts}

  // E3: reset restores the start state (by definition of the model; the shipped
  // implementation is checked by state_graph.py's reset probe).
  lemma E3_Reset(s: S) ensures Reset(s) == Start() {{}}

{e1_block}
  // Oracle entry points (compiled): apply one action to an explicit state.
  function Apply(x: int, y: int, rot: int, lives: int, steps: int, status: int, a: int): S
    requires 1 <= a <= 4
  {{ Step(S(x, y, rot, lives, steps, if status == 0 then Play else if status == 1 then Win else Over), a) }}
  function StatusCode(s: S): int {{ match s.status case Play => 0 case Win => 1 case Over => 2 }}
}}
'''


def border_facts(W: int, H: int) -> str:
    """Ground membership facts for every border cell, then the four quantified
    border statements by case split (the verifier decides ground membership in
    a set literal but not symbolic membership)."""
    L = ["  // The extracted wall set contains the whole border of the W x H lattice.",
         "  lemma BorderFacts()",
         "    ensures forall x :: 0 <= x < W ==> IsWall(x, 0) && IsWall(x, H - 1)",
         "    ensures forall y :: 0 <= y < H ==> IsWall(0, y) && IsWall(W - 1, y)",
         "  {"]
    L.append("    forall x | 0 <= x < W ensures IsWall(x, 0) && IsWall(x, H - 1) {")
    L.append("      " + " else ".join(f"if x == {x} {{ }}" for x in range(W)))
    L.append("    }")
    L.append("    forall y | 0 <= y < H ensures IsWall(0, y) && IsWall(W - 1, y) {")
    L.append("      " + " else ".join(f"if y == {y} {{ }}" for y in range(H)))
    L.append("    }")
    L.append("  }")
    return "\n".join(L) + "\n"


def e1_block(witness: list[int]) -> str:
    if not witness:
        return "  // E1: no witness yet (graph_L<k>.json absent); E1 is not claimed.\n"
    lines = ["  // E1: the level is winnable from its start; witness = shortest path found by",
             "  // enumerating the SHIPPED game (state_graph.py), replayed through the MODEL.",
             f"  const WITNESS: seq<int> := [{', '.join(str(x) for x in witness)}]",
             "  lemma E1_Winnable()",
             "    ensures Run(Start(), WITNESS).status == Win",
             "  {"]
    # Expose the computation one action at a time: s_i is the state after i actions.
    lines.append("    var s0 := Start();")
    for i, a in enumerate(witness):
        lines.append(f"    var s{i + 1} := Step(s{i}, {a});")
        lines.append(f"    assert Run(s{i}, WITNESS[{i}..]) == Run(s{i + 1}, WITNESS[{i + 1}..]);")
    lines.append(f"    assert Run(s{len(witness)}, WITNESS[{len(witness)}..]) == s{len(witness)};")
    lines.append("    assert WITNESS[0..] == WITNESS;")
    lines.append("  }")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--game", default="ls20")
    ap.add_argument("--level", type=int, default=1)
    a = ap.parse_args(argv)
    jp = ROOT / "artifacts" / "env" / a.game / f"level{a.level}.json"
    gp = ROOT / "artifacts" / "env" / a.game / f"graph_L{a.level}.json"
    d = json.loads(jp.read_text())
    assert not d["energy"] and not d["pushers"] and not d["patrol"] and not d["color_tiles"] and not d["shape_tiles"], "generator covers walls/goal/rotation-tile levels only"
    assert len(d["goals"]) == 1 and len(d["rotation_tiles"]) == 1
    witness = json.loads(gp.read_text()).get("shortest_win_path") if gp.exists() else None
    if not witness:
        witness = []
    steps_lemma = "    RunUnfold(Start(), WITNESS);\n"
    walls = "\n    || ".join(f"(x == {x} && y == {y})" for x, y in d["walls"])
    text = TEMPLATE.format(
        json_rel=jp.relative_to(ROOT), game=d["game"], level=a.level,
        cells_x=len(d["cells_x"]), cells_y=len(d["cells_y"]), sx=d["start"][0], sy=d["start"][1], srot=d["start_rotation_index"],
        gx=d["goals"][0]["cell"][0], gy=d["goals"][0]["cell"][1], grot=d["goals"][0]["rotation_index"],
        rx=d["rotation_tiles"][0][0], ry=d["rotation_tiles"][0][1], steps=d["step_counter"], dec=d["steps_decrement"], lives=d["lives"],
        walls=walls, e1_block=e1_block(witness), border_facts=border_facts(len(d["cells_x"]), len(d["cells_y"])),
    )
    # RunUnfold: a lemma that computes Run by unfolding.
    text = text.replace("  // Oracle entry points (compiled)", '''  lemma RunUnfold(s: S, path: seq<int>)
    requires forall i :: 0 <= i < |path| ==> 1 <= path[i] <= 4
    ensures Run(s, path) == (if |path| == 0 then s else Run(Step(s, path[0]), path[1..]))
    decreases |path|
  {}

  // Oracle entry points (compiled)''')
    out = ROOT / "model" / f"{a.game}_level{a.level}.dfy"
    out.write_text(text)
    print(f"wrote {out} (walls={len(d['walls'])}, witness_len={len(witness)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
