"""Generate INVENTORY.md from artefacts on disk. Never hand-edit INVENTORY.md.

Inputs (all optional; absent inputs produce explicit BLOCKED rows):
  vendor/PINS.json                              pinned commits
  artifacts/api/games.json                      /api/games listing saved by fetch_public_envs.py
  environment_files/<id>/<version>/metadata.json  fetched public environments (+ <id>.py source)
Flags: --run-offline  also instantiate each fetched environment in OFFLINE mode (executes its code).
"""
from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Public environments whose MECHANIC is described in the technical report v2 or the
# docs (checked by hand against artifacts/docs/report_v2.txt, 2026-09-04). A mention
# of a score or an action count is not a mechanic description.
DOCUMENTED = {
    "ls20": "report v2 Fig. 2 (screenshot), Fig. 3 (level-1 state graph, three-life mechanic, P_win = 1/355), Fig. 8 (actions by level)",
}
UNDOCUMENTED_MENTIONS = {
    "tr87": "report v2 §3.3: harness-sensitivity result (0.0% vs 97.1%), no mechanic",
    "bp35": "report v2 §3.3: 0.0% under both harnesses, no mechanic",
    "vc33": "report v2 §4.2: level 6 needs ~10x the actions of level 1, no mechanic",
    "re86": "report v2 Fig. 4: human action progression, no mechanic",
    "ft09": "report v2 §3.3: harness target, no mechanic",
}


def env_rows(env_dir: Path, run_offline: bool) -> list[dict]:
    rows = []
    for meta in sorted(env_dir.rglob("metadata.json")):
        m = json.loads(meta.read_text())
        gid = m.get("game_id", "?")
        base = gid.split("-", 1)[0]
        cls = m.get("class_name") or (base[0].upper() + base[1:])
        src = next((p for p in (meta.parent / f"{cls.lower()}.py", meta.parent / f"{cls}.py") if p.exists()), None)
        loc = sum(1 for l in src.read_text().splitlines() if l.strip() and not l.strip().startswith("#")) if src else None
        runs = "not attempted"
        if run_offline and src:
            try:
                from arc_agi import Arcade, OperationMode
                lg = logging.getLogger("inv"); lg.setLevel(logging.ERROR)
                arc = Arcade(operation_mode=OperationMode.OFFLINE, environments_dir=str(env_dir), logger=lg)
                env = arc.make(gid, save_recording=False)
                runs = "yes" if env is not None and env.observation_space is not None else "no"
            except Exception as e:  # noqa: BLE001
                runs = f"no ({type(e).__name__})"
        rows.append(dict(game_id=gid, title=m.get("title"), levels=len(m.get("baseline_actions") or []),
                         baseline_actions=m.get("baseline_actions"), source=str(src.relative_to(ROOT)) if src else None,
                         loc=loc, tags=m.get("tags"), runs_offline=runs, date_downloaded=m.get("date_downloaded")))
    return rows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-offline", action="store_true")
    ap.add_argument("--out", type=Path, default=ROOT / "INVENTORY.md")
    a = ap.parse_args(argv)
    pins = json.loads((ROOT / "vendor" / "PINS.json").read_text())
    games_path = ROOT / "artifacts" / "api" / "games.json"
    games = json.loads(games_path.read_text()) if games_path.exists() else None
    rows = env_rows(ROOT / "environment_files", a.run_offline) if (ROOT / "environment_files").exists() else []
    L = []
    L.append("# ARC-AGI-3 audit — inventory (generated by scripts/inventory.py; do not edit)\n")
    L.append("Scope: the 25 PUBLIC environments only. The semi-private and private sets are out of scope and are never fetched, probed or inferred.\n")
    L.append("## Pinned public repositories\n")
    L.append("| repo | commit | licence |\n|---|---|---|")
    for r, c in pins["commits"].items():
        L.append(f"| arcprize/{r} | `{c}` | MIT |")
    L.append("")
    L.append("## Where things live (from the pinned code)\n")
    L.append("- Environment source is NOT in any repo. `Arcade.make()` in NORMAL mode calls `_download_game` (vendor/ARC-AGI/arc_agi/base.py) which GETs `/api/games/{id}` for metadata and the game source, writes `environment_files/{id}/{version}/{metadata.json, <id>.py}`, then executes the source (`LocalEnvironmentWrapper._load_game_class`, `exec`). OFFLINE mode only scans `environment_files/**/metadata.json`.")
    L.append("- Transition logic = the downloaded `<id>.py` (an `ARCBaseGame` subclass) + the engine `arcengine` 0.9.3 from PyPI (`perform_action`, `handle_reset`, `full_reset`, `level_reset`, `next_level`).")
    L.append("- Per-level human baselines: `metadata.json.baseline_actions` (written by `_download_game` from the `/api/games/{id}` response; the toolkit's `_fetch_from_api` also reads `baseline_actions` from `/api/games`). The docs' published schema for `/api/games` omits the field; the real response is checked once fetched.")
    L.append("- Scoring: vendor/ARC-AGI/arc_agi/scorecard.py (`EnvironmentScoreCalculator`, `EnvironmentScorecard._calculate_score`). Action budget: vendor/arc-agi-3-benchmarking/benchmarking/agent.py (`MAX_ACTIONS_BASELINE_MULTIPLIER`, 5.0 in every shipped config; enforced per level in `is_done`).")
    L.append("")
    L.append("## API listing (`/api/games`)\n")
    if games is None:
        L.append("BLOCKED: not fetched in this repository yet. The anonymous key unlocks only 3 of 25 public games (docs: available-games); a registered key is needed for the full public set. Run `scripts/fetch_public_envs.py` with `ARC_API_KEY` set.\n")
    else:
        L.append(f"{len(games)} entries saved in `artifacts/api/games.json`. Fields present: {sorted({k for g in games for k in g})}. `baseline_actions` present in listing: {sum(1 for g in games if g.get('baseline_actions'))}/{len(games)}.\n")
    L.append("## Fetched public environments\n")
    if not rows:
        L.append("BLOCKED: no `environment_files/` on disk. Nothing has been downloaded or executed. Selection per the preregistered rule waits for the fetch.\n")
    else:
        L.append("| game_id | title | levels | baseline_actions | source | non-blank LOC | runs OFFLINE |\n|---|---|---|---|---|---|---|")
        for r in rows:
            L.append(f"| {r['game_id']} | {r['title']} | {r['levels']} | {r['baseline_actions']} | {r['source']} | {r['loc']} | {r['runs_offline']} |")
        L.append("")
        cands = [r for r in rows if r["levels"] >= 6 and r["loc"] is not None]
        cands.sort(key=lambda r: (r["loc"], r["game_id"]))
        L.append("## Selection (preregistered rule: fewest non-blank LOC with >= 6 levels and a documented mechanic)\n")
        L.append(f"Order by LOC (>= 6 levels): {', '.join(f'{r['game_id']} ({r['loc']})' for r in cands)}.\n")
        L.append("Documented mechanic (hand check of report v2 and docs):\n")
        for k, v in DOCUMENTED.items():
            L.append(f"- {k}: YES — {v}")
        for k, v in UNDOCUMENTED_MENTIONS.items():
            L.append(f"- {k}: mentioned, NO mechanic — {v}")
        L.append("- all others: not mentioned.\n")
        doc = [r for r in cands if r["game_id"].split("-")[0] in DOCUMENTED]
        if doc:
            L.append(f"Selected by the rule: **{doc[0]['game_id']}** ({doc[0]['loc']} LOC, {doc[0]['levels']} levels, baselines {doc[0]['baseline_actions']}). Cheaper candidates ({', '.join(r['game_id'].split('-')[0] for r in cands if r['loc'] < doc[0]['loc'])}) have no documented mechanic and are Phase 1 candidates.\n")
        else:
            L.append("No fetched environment satisfies all three clauses; the rule does not select.\n")
    census_p = ROOT / "artifacts" / "sweep" / "action_census.json"
    summary_p = ROOT / "artifacts" / "sweep" / "summary_L1.json"
    if census_p.exists():
        cen = {r["game"]: r for r in json.loads(census_p.read_text())}
        summ = {r["game"]: r for r in json.loads(summary_p.read_text())["rows"]} if summary_p.exists() else {}
        L.append("## Action space and level-1 enumeration (generated; scripts/action_census.py, scripts/sweep.py)\n")
        L.append("A game that advertises the click action has 64x64 targets per state, so its reachable")
        L.append("state graph cannot be enumerated exhaustively within any sane budget. That is a measured")
        L.append("property of the action space, not a judgement about the environment.\n")
        L.append("| game | actions | branching | enumerable | L1 status | states | win reachable | reset probe | double advance |")
        L.append("|---|---|---|---|---|---|---|---|---|")
        for k in sorted(cen):
            c = cen[k]; r = summ.get(k, {})
            win = r.get("win_reachable")
            win_s = "yes" if win is True else ("not established" if win is None and r.get("status") else "-")
            reset = f"{r['reset_returns_to_start']}/{r['reset_checked']}" if r.get("reset_checked") else "-"
            L.append(f"| {k} | {c['actions']} | {c['branching_factor']} | {'yes' if c['enumerable'] else 'no'} "
                     f"| {r.get('status', '-')} | {r.get('states', '-')} | {win_s} | {reset} | {r.get('double_advance_actions', '-')} |")
        enum = [k for k in cen if cen[k]["enumerable"]]
        done = [k for k, r in summ.items() if r.get("status") == "complete"]
        L.append(f"\nEnumerable action space: {len(enum)} of {len(cen)}. Level-1 enumeration complete within budget: "
                 f"{len(done)} ({', '.join(sorted(done))}); the rest stopped at a stated cap and establish nothing "
                 f"about reachability either way.\n")
    L.append(f"\nCounts: fetched={len(rows)}, listed={len(games) if games else 0}.\n")
    a.out.write_text("\n".join(L))
    print(f"wrote {a.out} (fetched={len(rows)}, listed={len(games) if games else 0})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
