"""Generate INVENTORY.md from artefacts on disk. Never hand-edit INVENTORY.md.

Inputs (all optional; absent inputs produce explicit BLOCKED rows):
  vendor/PINS.json                              pinned commits
  artifacts/api/games.json                      /api/games listing saved by fetch_public_envs.py
  environment_files/<id>/<version>/metadata.json  fetched public environments (+ <id>.py source)
Flags: --run-offline  also instantiate each fetched environment in OFFLINE mode (executes its code).
"""
from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def env_rows(env_dir: Path, run_offline: bool) -> list[dict]:
    rows = []
    for meta in sorted(env_dir.rglob("metadata.json")):
        m = json.loads(meta.read_text())
        gid = m.get("game_id", "?")
        base = gid.split("-", 1)[0]
        cls = m.get("class_name") or (base[0].upper() + base[1:])
        src = next((p for p in (meta.parent / f"{cls.lower()}.py", meta.parent / f"{cls}.py") if p.exists()), None)
        loc = sum(1 for l in src.read_text().splitlines() if l.strip() and not l.strip().startswith("#")) if src else None
        runs = "not attempted"
        if run_offline and src:
            try:
                from arc_agi import Arcade, OperationMode
                lg = logging.getLogger("inv"); lg.setLevel(logging.ERROR)
                arc = Arcade(operation_mode=OperationMode.OFFLINE, environments_dir=str(env_dir), logger=lg)
                env = arc.make(gid, save_recording=False)
                runs = "yes" if env is not None and env.observation_space is not None else "no"
            except Exception as e:  # noqa: BLE001
                runs = f"no ({type(e).__name__})"
        rows.append(dict(game_id=gid, title=m.get("title"), levels=len(m.get("baseline_actions") or []),
                         baseline_actions=m.get("baseline_actions"), source=str(src.relative_to(ROOT)) if src else None,
                         loc=loc, tags=m.get("tags"), runs_offline=runs, date_downloaded=m.get("date_downloaded")))
    return rows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-offline", action="store_true")
    ap.add_argument("--out", type=Path, default=ROOT / "INVENTORY.md")
    a = ap.parse_args(argv)
    pins = json.loads((ROOT / "vendor" / "PINS.json").read_text())
    games_path = ROOT / "artifacts" / "api" / "games.json"
    games = json.loads(games_path.read_text()) if games_path.exists() else None
    rows = env_rows(ROOT / "environment_files", a.run_offline) if (ROOT / "environment_files").exists() else []
    L = []
    L.append("# ARC-AGI-3 audit — inventory (generated by scripts/inventory.py; do not edit)\n")
    L.append("Scope: the 25 PUBLIC environments only. The semi-private and private sets are out of scope and are never fetched, probed or inferred.\n")
    L.append("## Pinned public repositories\n")
    L.append("| repo | commit | licence |\n|---|---|---|")
    for r, c in pins["commits"].items():
        L.append(f"| arcprize/{r} | `{c}` | MIT |")
    L.append("")
    L.append("## Where things live (from the pinned code)\n")
    L.append("- Environment source is NOT in any repo. `Arcade.make()` in NORMAL mode calls `_download_game` (vendor/ARC-AGI/arc_agi/base.py) which GETs `/api/games/{id}` for metadata and the game source, writes `environment_files/{id}/{version}/{metadata.json, <id>.py}`, then executes the source (`LocalEnvironmentWrapper._load_game_class`, `exec`). OFFLINE mode only scans `environment_files/**/metadata.json`.")
    L.append("- Transition logic = the downloaded `<id>.py` (an `ARCBaseGame` subclass) + the engine `arcengine` 0.9.3 from PyPI (`perform_action`, `handle_reset`, `full_reset`, `level_reset`, `next_level`).")
    L.append("- Per-level human baselines: `metadata.json.baseline_actions` (written by `_download_game` from the `/api/games/{id}` response; the toolkit's `_fetch_from_api` also reads `baseline_actions` from `/api/games`). The docs' published schema for `/api/games` omits the field; the real response is checked once fetched.")
    L.append("- Scoring: vendor/ARC-AGI/arc_agi/scorecard.py (`EnvironmentScoreCalculator`, `EnvironmentScorecard._calculate_score`). Action budget: vendor/arc-agi-3-benchmarking/benchmarking/agent.py (`MAX_ACTIONS_BASELINE_MULTIPLIER`, 5.0 in every shipped config; enforced per level in `is_done`).")
    L.append("")
    L.append("## API listing (`/api/games`)\n")
    if games is None:
        L.append("BLOCKED: not fetched in this repository yet. The anonymous key unlocks only 3 of 25 public games (docs: available-games); a registered key is needed for the full public set. Run `scripts/fetch_public_envs.py` with `ARC_API_KEY` set.\n")
    else:
        L.append(f"{len(games)} entries saved in `artifacts/api/games.json`. Fields present: {sorted({k for g in games for k in g})}. `baseline_actions` present in listing: {sum(1 for g in games if g.get('baseline_actions'))}/{len(games)}.\n")
    L.append("## Fetched public environments\n")
    if not rows:
        L.append("BLOCKED: no `environment_files/` on disk. Nothing has been downloaded or executed. Selection per the preregistered rule waits for the fetch.\n")
    else:
        L.append("| game_id | title | levels | baseline_actions | source | non-blank LOC | runs OFFLINE |\n|---|---|---|---|---|---|---|")
        for r in rows:
            L.append(f"| {r['game_id']} | {r['title']} | {r['levels']} | {r['baseline_actions']} | {r['source']} | {r['loc']} | {r['runs_offline']} |")
        L.append("")
        cands = [r for r in rows if r["levels"] >= 6 and r["loc"] is not None]
        cands.sort(key=lambda r: (r["loc"], r["game_id"]))
        L.append("## Selection (preregistered rule: fewest non-blank LOC with >= 6 levels and a documented mechanic)\n")
        if cands:
            L.append(f"Candidate order by LOC: {', '.join(f'{r['game_id']} ({r['loc']})' for r in cands[:8])}.")
            L.append(f"Selected by the rule: **{cands[0]['game_id']}** ({cands[0]['loc']} LOC, {cands[0]['levels']} levels). The 'documented mechanic' criterion is checked by hand and recorded in docs/DECISIONS.md before modelling.\n")
        else:
            L.append("No fetched environment has >= 6 levels; the rule does not select. Recorded, not resolved by hand.\n")
    L.append(f"\nCounts: fetched={len(rows)}, listed={len(games) if games else 0}.\n")
    a.out.write_text("\n".join(L))
    print(f"wrote {a.out} (fetched={len(rows)}, listed={len(games) if games else 0})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
