// GENERATED by scripts/gen_level_model.py from artifacts/env/ls20/level1.json; do not edit.
// Rule-level model of ARC-AGI-3 public environment ls20-9607627b, level 1.
// No escape constructs (checked by scripts/check_model.sh).
module Ls20Level1 {
  const W: int := 12
  const H: int := 12
  const START_X: int := 6
  const START_Y: int := 9
  const START_ROT: int := 3
  const GOAL_X: int := 6
  const GOAL_Y: int := 2
  const GOAL_ROT: int := 0
  const ROT_TILE_X: int := 3
  const ROT_TILE_Y: int := 6
  const STEPS: int := 42
  const DEC: int := 1
  const LIVES: int := 3
  // Wall cells, from the shipped level data (one disjunct per cell).
  predicate IsWall(x: int, y: int) {
    (x == 0 && y == 0)
    || (x == 0 && y == 1)
    || (x == 0 && y == 2)
    || (x == 0 && y == 3)
    || (x == 0 && y == 4)
    || (x == 0 && y == 5)
    || (x == 0 && y == 6)
    || (x == 0 && y == 7)
    || (x == 0 && y == 8)
    || (x == 0 && y == 9)
    || (x == 0 && y == 10)
    || (x == 0 && y == 11)
    || (x == 1 && y == 0)
    || (x == 1 && y == 1)
    || (x == 1 && y == 2)
    || (x == 1 && y == 3)
    || (x == 1 && y == 4)
    || (x == 1 && y == 5)
    || (x == 1 && y == 6)
    || (x == 1 && y == 7)
    || (x == 1 && y == 8)
    || (x == 1 && y == 9)
    || (x == 1 && y == 10)
    || (x == 1 && y == 11)
    || (x == 2 && y == 0)
    || (x == 2 && y == 1)
    || (x == 2 && y == 2)
    || (x == 2 && y == 3)
    || (x == 2 && y == 4)
    || (x == 2 && y == 8)
    || (x == 2 && y == 9)
    || (x == 2 && y == 10)
    || (x == 2 && y == 11)
    || (x == 3 && y == 0)
    || (x == 3 && y == 1)
    || (x == 3 && y == 2)
    || (x == 3 && y == 3)
    || (x == 3 && y == 4)
    || (x == 3 && y == 10)
    || (x == 3 && y == 11)
    || (x == 4 && y == 0)
    || (x == 4 && y == 1)
    || (x == 4 && y == 2)
    || (x == 4 && y == 3)
    || (x == 4 && y == 4)
    || (x == 4 && y == 8)
    || (x == 4 && y == 10)
    || (x == 4 && y == 11)
    || (x == 5 && y == 0)
    || (x == 5 && y == 1)
    || (x == 5 && y == 2)
    || (x == 5 && y == 3)
    || (x == 5 && y == 4)
    || (x == 5 && y == 6)
    || (x == 5 && y == 7)
    || (x == 5 && y == 8)
    || (x == 5 && y == 10)
    || (x == 5 && y == 11)
    || (x == 6 && y == 0)
    || (x == 6 && y == 1)
    || (x == 6 && y == 10)
    || (x == 6 && y == 11)
    || (x == 7 && y == 0)
    || (x == 7 && y == 1)
    || (x == 7 && y == 2)
    || (x == 7 && y == 3)
    || (x == 7 && y == 4)
    || (x == 7 && y == 10)
    || (x == 7 && y == 11)
    || (x == 8 && y == 0)
    || (x == 8 && y == 1)
    || (x == 8 && y == 2)
    || (x == 8 && y == 3)
    || (x == 8 && y == 4)
    || (x == 8 && y == 10)
    || (x == 8 && y == 11)
    || (x == 9 && y == 0)
    || (x == 9 && y == 1)
    || (x == 9 && y == 2)
    || (x == 9 && y == 3)
    || (x == 9 && y == 4)
    || (x == 9 && y == 10)
    || (x == 9 && y == 11)
    || (x == 10 && y == 0)
    || (x == 10 && y == 1)
    || (x == 10 && y == 2)
    || (x == 10 && y == 3)
    || (x == 10 && y == 4)
    || (x == 10 && y == 5)
    || (x == 10 && y == 6)
    || (x == 10 && y == 7)
    || (x == 10 && y == 8)
    || (x == 10 && y == 9)
    || (x == 10 && y == 10)
    || (x == 10 && y == 11)
    || (x == 11 && y == 0)
    || (x == 11 && y == 1)
    || (x == 11 && y == 2)
    || (x == 11 && y == 3)
    || (x == 11 && y == 4)
    || (x == 11 && y == 5)
    || (x == 11 && y == 6)
    || (x == 11 && y == 7)
    || (x == 11 && y == 8)
    || (x == 11 && y == 9)
    || (x == 11 && y == 10)
    || (x == 11 && y == 11)
  }

  datatype Status = Play | Win | Over
  datatype S = S(x: int, y: int, rot: int, lives: int, steps: int, status: Status)

  predicate Legal(s: S) {
    0 <= s.x < W && 0 <= s.y < H && !IsWall(s.x, s.y) && 0 <= s.rot < 4 && 1 <= s.lives <= LIVES && -DEC <= s.steps <= STEPS
  }

  lemma StartLegal() ensures Legal(Start()) {}


  function Start(): S { S(START_X, START_Y, START_ROT, LIVES, STEPS, Play) }

  function Delta(a: int): (int, int)
    requires 1 <= a <= 4
  { if a == 1 then (0, -1) else if a == 2 then (0, 1) else if a == 3 then (-1, 0) else (1, 0) }

  predicate Matches(rot: int) { rot == GOAL_ROT }

  // One action on a Play state. Mirrors Ls20.step() at the rule level.
  function Step(s: S, a: int): S
    requires 1 <= a <= 4
  {
    if s.status != Play then s else
    var d := Delta(a);
    var tx := s.x + d.0;
    var ty := s.y + d.1;
    var isWall := IsWall(tx, ty);
    var isGoal := tx == GOAL_X && ty == GOAL_Y;
    var isRot := tx == ROT_TILE_X && ty == ROT_TILE_Y;
    // rotation tile: cycle; on level 1 a resulting match "flashes" (no step cost)
    var rot' := if !isWall && isRot then (s.rot + 1) % 4 else s.rot;
    var flash := (!isWall && isGoal && !Matches(s.rot)) || (!isWall && isRot && Matches(rot'));
    var blocked := isWall || (isGoal && !Matches(s.rot));
    var x' := if blocked then s.x else tx;
    var y' := if blocked then s.y else ty;
    if flash then S(x', y', rot', s.lives, s.steps, Play) else
    var steps' := if s.steps >= 0 then s.steps - DEC else s.steps;
    var ranOut := steps' < 0;
    var won := x' == GOAL_X && y' == GOAL_Y && Matches(rot');
    if won then S(x', y', rot', s.lives, steps', Win) else
    if ranOut then (
      if s.lives - 1 == 0 then S(x', y', rot', 0, steps', Over)
      else S(START_X, START_Y, START_ROT, s.lives - 1, STEPS, Play))
    else S(x', y', rot', s.lives, steps', Play)
  }

  function Reset(s: S): S { Start() }

  function Run(s: S, path: seq<int>): S
    requires forall i :: 0 <= i < |path| ==> 1 <= path[i] <= 4
    decreases |path|
  { if |path| == 0 then s else Run(Step(s, path[0]), path[1..]) }

  // E2: no action leaves the legal state space (Over states carry lives = 0 and are terminal).
  predicate LegalOrOver(s: S) { Legal(s) || (s.status == Over && s.lives == 0) }

  lemma E2_Closure(s: S, a: int)
    requires 1 <= a <= 4
    requires Legal(s)
    ensures LegalOrOver(Step(s, a))
  {
    // The player never stands on a wall cell and the border is walled, so a
    // legal position is interior and every neighbour is in range; a blocked
    // move keeps the position, an unblocked one lands on a non-wall cell.
    BorderFacts();
    assert 1 <= s.x <= W - 2 && 1 <= s.y <= H - 2;
  }

  // The extracted wall set contains the whole border of the W x H lattice.
  lemma BorderFacts()
    ensures forall x :: 0 <= x < W ==> IsWall(x, 0) && IsWall(x, H - 1)
    ensures forall y :: 0 <= y < H ==> IsWall(0, y) && IsWall(W - 1, y)
  {
    forall x | 0 <= x < W ensures IsWall(x, 0) && IsWall(x, H - 1) {
      if x == 0 { } else if x == 1 { } else if x == 2 { } else if x == 3 { } else if x == 4 { } else if x == 5 { } else if x == 6 { } else if x == 7 { } else if x == 8 { } else if x == 9 { } else if x == 10 { } else if x == 11 { }
    }
    forall y | 0 <= y < H ensures IsWall(0, y) && IsWall(W - 1, y) {
      if y == 0 { } else if y == 1 { } else if y == 2 { } else if y == 3 { } else if y == 4 { } else if y == 5 { } else if y == 6 { } else if y == 7 { } else if y == 8 { } else if y == 9 { } else if y == 10 { } else if y == 11 { }
    }
  }


  // E3: reset restores the start state (by definition of the model; the shipped
  // implementation is checked by state_graph.py's reset probe).
  lemma E3_Reset(s: S) ensures Reset(s) == Start() {}

  // E1: the level is winnable from its start; witness = shortest path found by
  // enumerating the SHIPPED game (state_graph.py), replayed through the MODEL.
  const WITNESS: seq<int> := [3, 3, 3, 1, 1, 1, 1, 4, 4, 4, 1, 1, 1]
  lemma E1_Winnable()
    ensures Run(Start(), WITNESS).status == Win
  {
    var s0 := Start();
    var s1 := Step(s0, 3);
    assert Run(s0, WITNESS[0..]) == Run(s1, WITNESS[1..]);
    var s2 := Step(s1, 3);
    assert Run(s1, WITNESS[1..]) == Run(s2, WITNESS[2..]);
    var s3 := Step(s2, 3);
    assert Run(s2, WITNESS[2..]) == Run(s3, WITNESS[3..]);
    var s4 := Step(s3, 1);
    assert Run(s3, WITNESS[3..]) == Run(s4, WITNESS[4..]);
    var s5 := Step(s4, 1);
    assert Run(s4, WITNESS[4..]) == Run(s5, WITNESS[5..]);
    var s6 := Step(s5, 1);
    assert Run(s5, WITNESS[5..]) == Run(s6, WITNESS[6..]);
    var s7 := Step(s6, 1);
    assert Run(s6, WITNESS[6..]) == Run(s7, WITNESS[7..]);
    var s8 := Step(s7, 4);
    assert Run(s7, WITNESS[7..]) == Run(s8, WITNESS[8..]);
    var s9 := Step(s8, 4);
    assert Run(s8, WITNESS[8..]) == Run(s9, WITNESS[9..]);
    var s10 := Step(s9, 4);
    assert Run(s9, WITNESS[9..]) == Run(s10, WITNESS[10..]);
    var s11 := Step(s10, 1);
    assert Run(s10, WITNESS[10..]) == Run(s11, WITNESS[11..]);
    var s12 := Step(s11, 1);
    assert Run(s11, WITNESS[11..]) == Run(s12, WITNESS[12..]);
    var s13 := Step(s12, 1);
    assert Run(s12, WITNESS[12..]) == Run(s13, WITNESS[13..]);
    assert Run(s13, WITNESS[13..]) == s13;
    assert WITNESS[0..] == WITNESS;
  }

  lemma RunUnfold(s: S, path: seq<int>)
    requires forall i :: 0 <= i < |path| ==> 1 <= path[i] <= 4
    ensures Run(s, path) == (if |path| == 0 then s else Run(Step(s, path[0]), path[1..]))
    decreases |path|
  {}

  // Oracle entry points (compiled): apply one action to an explicit state.
  function Apply(x: int, y: int, rot: int, lives: int, steps: int, status: int, a: int): S
    requires 1 <= a <= 4
  { Step(S(x, y, rot, lives, steps, if status == 0 then Play else if status == 1 then Win else Over), a) }
  function StatusCode(s: S): int { match s.status case Play => 0 case Win => 1 case Over => 2 }
}
