// GENERATED by scripts/gen_level_model.py from artifacts/env/ls20/level1.json; do not edit.
// Rule-level model of ARC-AGI-3 public environment ls20-9607627b, level 1.
// Constants from the shipped level data; rules from reading the shipped source
// (see the generator's docstring). No escape constructs; see scripts/check_model.sh.
module Ls20Level1 {
  const W: int := 12
  const H: int := 12
  const START_X: int := 6
  const START_Y: int := 9
  const START_ROT: int := 3
  const GOAL_X: int := 6
  const GOAL_Y: int := 2
  const GOAL_ROT: int := 0
  const ROT_TILE_X: int := 3
  const ROT_TILE_Y: int := 6
  const STEPS: int := 42
  const DEC: int := 1
  const LIVES: int := 3
  const NE: int := 0          // energy pickups on this level
  const TILE_FLASH: bool := true  // cycling a tile into a match is free (level 1 only)

  // Wall cells, from the shipped level data (one disjunct per cell).
  predicate IsWall(x: int, y: int) {
    (x == 0 && y == 0)
    || (x == 0 && y == 1)
    || (x == 0 && y == 2)
    || (x == 0 && y == 3)
    || (x == 0 && y == 4)
    || (x == 0 && y == 5)
    || (x == 0 && y == 6)
    || (x == 0 && y == 7)
    || (x == 0 && y == 8)
    || (x == 0 && y == 9)
    || (x == 0 && y == 10)
    || (x == 0 && y == 11)
    || (x == 1 && y == 0)
    || (x == 1 && y == 1)
    || (x == 1 && y == 2)
    || (x == 1 && y == 3)
    || (x == 1 && y == 4)
    || (x == 1 && y == 5)
    || (x == 1 && y == 6)
    || (x == 1 && y == 7)
    || (x == 1 && y == 8)
    || (x == 1 && y == 9)
    || (x == 1 && y == 10)
    || (x == 1 && y == 11)
    || (x == 2 && y == 0)
    || (x == 2 && y == 1)
    || (x == 2 && y == 2)
    || (x == 2 && y == 3)
    || (x == 2 && y == 4)
    || (x == 2 && y == 8)
    || (x == 2 && y == 9)
    || (x == 2 && y == 10)
    || (x == 2 && y == 11)
    || (x == 3 && y == 0)
    || (x == 3 && y == 1)
    || (x == 3 && y == 2)
    || (x == 3 && y == 3)
    || (x == 3 && y == 4)
    || (x == 3 && y == 10)
    || (x == 3 && y == 11)
    || (x == 4 && y == 0)
    || (x == 4 && y == 1)
    || (x == 4 && y == 2)
    || (x == 4 && y == 3)
    || (x == 4 && y == 4)
    || (x == 4 && y == 8)
    || (x == 4 && y == 10)
    || (x == 4 && y == 11)
    || (x == 5 && y == 0)
    || (x == 5 && y == 1)
    || (x == 5 && y == 2)
    || (x == 5 && y == 3)
    || (x == 5 && y == 4)
    || (x == 5 && y == 6)
    || (x == 5 && y == 7)
    || (x == 5 && y == 8)
    || (x == 5 && y == 10)
    || (x == 5 && y == 11)
    || (x == 6 && y == 0)
    || (x == 6 && y == 1)
    || (x == 6 && y == 10)
    || (x == 6 && y == 11)
    || (x == 7 && y == 0)
    || (x == 7 && y == 1)
    || (x == 7 && y == 2)
    || (x == 7 && y == 3)
    || (x == 7 && y == 4)
    || (x == 7 && y == 10)
    || (x == 7 && y == 11)
    || (x == 8 && y == 0)
    || (x == 8 && y == 1)
    || (x == 8 && y == 2)
    || (x == 8 && y == 3)
    || (x == 8 && y == 4)
    || (x == 8 && y == 10)
    || (x == 8 && y == 11)
    || (x == 9 && y == 0)
    || (x == 9 && y == 1)
    || (x == 9 && y == 2)
    || (x == 9 && y == 3)
    || (x == 9 && y == 4)
    || (x == 9 && y == 10)
    || (x == 9 && y == 11)
    || (x == 10 && y == 0)
    || (x == 10 && y == 1)
    || (x == 10 && y == 2)
    || (x == 10 && y == 3)
    || (x == 10 && y == 4)
    || (x == 10 && y == 5)
    || (x == 10 && y == 6)
    || (x == 10 && y == 7)
    || (x == 10 && y == 8)
    || (x == 10 && y == 9)
    || (x == 10 && y == 10)
    || (x == 10 && y == 11)
    || (x == 11 && y == 0)
    || (x == 11 && y == 1)
    || (x == 11 && y == 2)
    || (x == 11 && y == 3)
    || (x == 11 && y == 4)
    || (x == 11 && y == 5)
    || (x == 11 && y == 6)
    || (x == 11 && y == 7)
    || (x == 11 && y == 8)
    || (x == 11 && y == 9)
    || (x == 11 && y == 10)
    || (x == 11 && y == 11)
  }

  function EnergyIndex(x: int, y: int): int { -1 }

  // The 1 legal value(s) of the energy bitmask for NE = 0.
  predicate EatenLegal(m: nat) { m == 0 }

  function AddBit(m: nat, i: int): nat
    requires 0 <= i < NE
  {
    m  // unreachable: the precondition is unsatisfiable when NE == 0
  }

  predicate HasBit(m: nat, i: int)
    requires 0 <= i < NE
  {
    false  // unreachable: the precondition is unsatisfiable when NE == 0
  }

  datatype Status = Play | Win | Over
  datatype S = S(x: int, y: int, rot: int, lives: int, steps: int, eaten: nat, status: Status)

  predicate Legal(s: S) {
    0 <= s.x < W && 0 <= s.y < H && !IsWall(s.x, s.y) && 0 <= s.rot < 4
    && 1 <= s.lives <= LIVES && -DEC <= s.steps <= STEPS && EatenLegal(s.eaten)
  }

  function Start(): S { S(START_X, START_Y, START_ROT, LIVES, STEPS, 0, Play) }

  lemma StartLegal() ensures Legal(Start()) {}

  function Delta(a: int): (int, int)
  { if a == 1 then (0, -1) else if a == 2 then (0, 1) else if a == 3 then (-1, 0)
     else if a == 4 then (1, 0) else (0, 0) }

  predicate Matches(rot: int) { rot == GOAL_ROT }

  // One action on a Play state. Mirrors Ls20.step() at the rule level.
  // TOTAL in the action: an action outside the movement set leaves the state
  // untouched, which is what the shipped game does -- it completes the action
  // and returns before the step counter is touched.
  function Step(s: S, a: int): S
  {
    if s.status != Play || a < 1 || a > 4 then s else
    var d := Delta(a);
    var tx := s.x + d.0;
    var ty := s.y + d.1;
    var isWall := IsWall(tx, ty);
    var isGoal := tx == GOAL_X && ty == GOAL_Y;
    var isRot := tx == ROT_TILE_X && ty == ROT_TILE_Y;
    var ei := EnergyIndex(tx, ty);
    var gotEnergy := !isWall && ei >= 0 && ei < NE && !HasBit(s.eaten, ei);
    var rot' := if !isWall && isRot then (s.rot + 1) % 4 else s.rot;
    // A flash consumes the action at no step cost: a goal reached with the wrong
    // rotation always flashes; a tile cycled into a match flashes on level 1 only.
    var flash := (!isWall && isGoal && !Matches(s.rot))
              || (TILE_FLASH && !isWall && isRot && Matches(rot'));
    var blocked := isWall || (isGoal && !Matches(s.rot));
    var x' := if blocked then s.x else tx;
    var y' := if blocked then s.y else ty;
    var eaten' := if gotEnergy then AddBit(s.eaten, ei) else s.eaten;
    if flash then S(x', y', rot', s.lives, s.steps, eaten', Play) else
    // An energy pickup refills the counter and skips this move's decrement.
    if gotEnergy then S(x', y', rot', s.lives, STEPS, eaten', Play) else
    var steps' := if s.steps >= 0 then s.steps - DEC else s.steps;
    var ranOut := steps' < 0;
    var won := x' == GOAL_X && y' == GOAL_Y && Matches(rot');
    if won then S(x', y', rot', s.lives, steps', eaten', Win) else
    if ranOut then (
      if s.lives - 1 == 0 then S(x', y', rot', 0, steps', eaten', Over)
      else S(START_X, START_Y, START_ROT, s.lives - 1, STEPS, 0, Play))
    else S(x', y', rot', s.lives, steps', eaten', Play)
  }

  function Reset(s: S): S { Start() }

  // Indexed rather than sliced: slicing a 45-element literal sequence put the
  // prover into work it could not finish, and an unfinished obligation is
  // unknown, not discharged.
  function RunFrom(s: S, path: seq<int>, i: nat): S
    requires i <= |path|
    decreases |path| - i
  { if i == |path| then s else RunFrom(Step(s, path[i]), path, i + 1) }

  function Run(s: S, path: seq<int>): S { RunFrom(s, path, 0) }

  // A non-movement action changes nothing (the shipped game returns before the
  // step counter is touched); this is what makes Step total.
  lemma NoOpAction(s: S, a: int)
    requires a < 1 || a > 4
    ensures Step(s, a) == s
  {}

  // E2: no action leaves the legal state space (an Over state is terminal and
  // carries lives = 0). The player is never on a wall cell and the border is
  // walled, so a legal position is interior and every neighbour is in range.
  predicate LegalOrOver(s: S) { Legal(s) || (s.status == Over && s.lives == 0) }

  lemma E2_Closure(s: S, a: int)
    requires Legal(s)
    ensures LegalOrOver(Step(s, a))
  {
    if 1 <= a <= 4 {
      BorderFacts();
      assert 1 <= s.x <= W - 2 && 1 <= s.y <= H - 2;
    }
    EatenBound(s, a);
  }

  // The eaten bitmask stays legal: a pickup is consumed at most once, and the
  // mask space is enumerated explicitly (it has at most 2^NE elements, NE small),
  // so this is decided by case analysis rather than nonlinear arithmetic.
  lemma EatenBound(s: S, a: int)
    requires Legal(s)
    ensures EatenLegal(Step(s, a).eaten)
  {
    if 1 <= a <= 4 {
      var d := Delta(a);
      var ei := EnergyIndex(s.x + d.0, s.y + d.1);
      if 0 <= ei < NE && !HasBit(s.eaten, ei) {
        EatenClosure(s.eaten, ei);
      }
    }
  }

  lemma EatenClosure(m: nat, i: int)
    requires EatenLegal(m) && 0 <= i < NE && !HasBit(m, i)
    ensures EatenLegal(AddBit(m, i))
  {}

  // The extracted wall set contains the whole border of the W x H lattice.
  lemma BorderFacts()
    ensures forall x :: 0 <= x < W ==> IsWall(x, 0) && IsWall(x, H - 1)
    ensures forall y :: 0 <= y < H ==> IsWall(0, y) && IsWall(W - 1, y)
  {
    forall x | 0 <= x < W ensures IsWall(x, 0) && IsWall(x, H - 1) {
      if x == 0 { } else if x == 1 { } else if x == 2 { } else if x == 3 { } else if x == 4 { } else if x == 5 { } else if x == 6 { } else if x == 7 { } else if x == 8 { } else if x == 9 { } else if x == 10 { } else if x == 11 { }
    }
    forall y | 0 <= y < H ensures IsWall(0, y) && IsWall(W - 1, y) {
      if y == 0 { } else if y == 1 { } else if y == 2 { } else if y == 3 { } else if y == 4 { } else if y == 5 { } else if y == 6 { } else if y == 7 { } else if y == 8 { } else if y == 9 { } else if y == 10 { } else if y == 11 { }
    }
  }

  // E3: reset restores the start state (by definition in the model; the shipped
  // implementation is probed directly by scripts/state_graph.py).
  lemma E3_Reset(s: S) ensures Reset(s) == Start() {}

  // E1: winnable. WITNESS is the shortest winning action sequence found by
  // enumerating the SHIPPED game; each intermediate state asserted below is
  // that game's actual state after those actions, so the proof checks the
  // model against the implementation at every step of the winning path.
  // The last state is checked on status alone: the shipped game has loaded
  // the next level by then, which this model does not cover.
  const WITNESS: seq<int> := [3, 3, 3, 1, 1, 1, 1, 4, 4, 4, 1, 1, 1]  // 13 actions

  function Chunk0(s: S): S { Step(Step(Step(Step(Step(Step(Step(Step(Step(Step(s, 3), 3), 3), 1), 1), 1), 1), 4), 4), 4) }
  function Chunk1(s: S): S { Step(Step(Step(s, 1), 1), 1) }

  function PlayWitness(s: S): S { Chunk1(Chunk0(s)) }

  lemma E1_Chunk0()
    ensures Chunk0(S(6, 9, 3, 3, 42, 0, Play)) == S(6, 5, 0, 3, 33, 0, Play)
  {
    var s0 := S(6, 9, 3, 3, 42, 0, Play);
    var s1 := Step(s0, 3);
    assert s1 == S(5, 9, 3, 3, 41, 0, Play);  // the shipped game after 1 action(s)
    var s2 := Step(s1, 3);
    assert s2 == S(4, 9, 3, 3, 40, 0, Play);  // the shipped game after 2 action(s)
    var s3 := Step(s2, 3);
    assert s3 == S(3, 9, 3, 3, 39, 0, Play);  // the shipped game after 3 action(s)
    var s4 := Step(s3, 1);
    assert s4 == S(3, 8, 3, 3, 38, 0, Play);  // the shipped game after 4 action(s)
    var s5 := Step(s4, 1);
    assert s5 == S(3, 7, 3, 3, 37, 0, Play);  // the shipped game after 5 action(s)
    var s6 := Step(s5, 1);
    assert s6 == S(3, 6, 0, 3, 37, 0, Play);  // the shipped game after 6 action(s)
    var s7 := Step(s6, 1);
    assert s7 == S(3, 5, 0, 3, 36, 0, Play);  // the shipped game after 7 action(s)
    var s8 := Step(s7, 4);
    assert s8 == S(4, 5, 0, 3, 35, 0, Play);  // the shipped game after 8 action(s)
    var s9 := Step(s8, 4);
    assert s9 == S(5, 5, 0, 3, 34, 0, Play);  // the shipped game after 9 action(s)
    var s10 := Step(s9, 4);
    assert s10 == S(6, 5, 0, 3, 33, 0, Play);  // the shipped game after 10 action(s)
  }

  lemma E1_Chunk1()
    ensures Chunk1(S(6, 5, 0, 3, 33, 0, Play)).status == Win
  {
    var s10 := S(6, 5, 0, 3, 33, 0, Play);
    var s11 := Step(s10, 1);
    assert s11 == S(6, 4, 0, 3, 32, 0, Play);  // the shipped game after 11 action(s)
    var s12 := Step(s11, 1);
    assert s12 == S(6, 3, 0, 3, 31, 0, Play);  // the shipped game after 12 action(s)
    var s13 := Step(s12, 1);
    assert s13.status == Win;
  }

  lemma E1_Winnable()
    ensures |WITNESS| == 13
    ensures PlayWitness(Start()).status == Win
  {
    assert Start() == S(6, 9, 3, 3, 42, 0, Play);
    E1_Chunk0();
    E1_Chunk1();
  }

  // Oracle entry points (compiled to JavaScript and called by the differential).
  function Apply(x: int, y: int, rot: int, lives: int, steps: int, eaten: nat, status: int, a: int): S
  { Step(S(x, y, rot, lives, steps, eaten, if status == 0 then Play else if status == 1 then Win else Over), a) }
  function StatusCode(s: S): int { match s.status case Play => 0 case Win => 1 case Over => 2 }
}
